tasks:
  - init: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - tabnine.tabnine-vscode
